# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Tommy Becker
tagline:          'A Website Thing'
description:      'This is my website.'
url:              https://mockmyberet.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Tommy Becker'
  url:            https://twitter.com/mockmyberet

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-admin

# Custom vars
version:            1.0
sidebar_home_link:  false
future:             false
#github:
#  repo:             https://github.com/mockmyberet
disqus:
  shortname: mockmyberet
